name: Convert BiRefNet to CoreML

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  convert:
    runs-on: ubuntu-latest

    env:
      TRANSFORMERS_NO_ADVISORY_WARNINGS: "1"
      HF_HUB_DISABLE_TELEMETRY: "1"
      HF_HUB_OFFLINE: "0"
      HF_HUB_ENABLE_HF_TRANSFER: "1"
      HF_HUB_DISABLE_PROGRESS_BARS: "1"
      HF_ALLOW_CODE_EXECUTION: "1"   # ✅ Auto-trust remote code
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install torch torchvision torchaudio
          pip install coremltools==7.2
          pip install pillow transformers timm kornia einops
          pip install hf_transfer   # ✅ Fix: Add this for Hugging Face fast download

      - name: Convert BiRefNet to CoreML
        run: |
          python3 - <<'EOF'
          import torch
          import coremltools as ct
          from transformers import AutoModelForImageSegmentation

          print("🚀 Loading BiRefNet model (lite) with trust_remote_code=True...")
          model = AutoModelForImageSegmentation.from_pretrained(
              "ZhengPeng7/BiRefNet_lite",
              trust_remote_code=True
          )
          model.eval()

          example_input = torch.rand(1, 3, 512, 512)
          print("⚡ Tracing model...")
          traced = torch.jit.trace(model, example_input)
          traced.save("birefnet_lite_traced.pt")

          print("🧠 Converting to CoreML...")
          mlmodel = ct.convert(
              traced,
              inputs=[ct.ImageType(name="input_image", shape=example_input.shape, scale=1/255.0)],
              convert_to="mlprogram",
              compute_units=ct.ComputeUnit.ALL,
          )

          print("📦 Optimizing precision (FP16)...")
          mlmodel = ct.models.neural_network.quantization_utils.quantize_weights(mlmodel, nbits=16)
          mlmodel.save("BiRefNetBackgroundRemoval.mlmodel")
          print("✅ Done — BiRefNetBackgroundRemoval.mlmodel created successfully.")
          EOF

      - name: Upload CoreML Model
        uses: actions/upload-artifact@v4
        with:
          name: BiRefNetBackgroundRemoval
          path: BiRefNetBackgroundRemoval.mlmodel
